name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Esto es la magia: le dice a GitHub que no use sus servidores,
    # sino que mande el trabajo a tu Raspberry Pi.
    runs-on: self-hosted

    steps:
      - name: Actualizar y levantar contenedores
        # Al estar en tu Raspberry, podemos ejecutar los comandos directamente
        run: |
          cd /home/jesus/docker/compose/job-radar
          git pull origin main
          docker compose down
          docker system prune -af
          docker compose up --build -d
